#!/usr/bin/env bash
# Configures Nginx redirection

# Update package index
apt-get update

# Install nginx
apt-get install -y nginx

# Make sure nginx is listening on port 80
sed -i 's/80 default_server/80 default_server/g' /etc/nginx/sites-available/default

# Configure redirection
echo "
server {
    listen 80;
    listen [::]:80;

    server_name _;

    location /redirect_me {
        return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
    }
}
" > /etc/nginx/sites-available/default

# Restart nginx
service nginx restart

