#!/usr/bin/env bash
# Configures custom 404 page in Nginx

# Update package index
apt-get update

# Install nginx
apt-get install -y nginx

# Make sure nginx is listening on port 80
sed -i 's/80 default_server/80 default_server/g' /etc/nginx/sites-available/default

# Configure custom 404 page
echo "
server {
    listen 80 default_server;
    listen [::]:80 default_server;

    root /var/www/html;
    index index.html index.htm;

    server_name _;

    error_page 404 /404.html;
    location = /404.html {
        internal;
        root /usr/share/nginx/html;
    }

    location / {
        try_files $uri $uri/ =404;
    }
}
" > /etc/nginx/sites-available/default

# Create custom 404 page
echo "Ceci n'est pas une page" > /usr/share/nginx/html/404.html

# Restart nginx
service nginx restart

