#!/usr/bin/env bash
# This script answers questions about different types of networks.
# It provides information about LAN, WAN, and Internet connections.

What type of network a computer in local is connected to?
Answer: LAN

What type of network could connect an office in one building to another office in a building a few streets away?
Answer: WAN

What network do you use when you browse www.google.com from your smartphone (not connected to the Wifi)?
Answer: Internet

