#!/usr/bin/env bash
# Check if Nginx is installed
if ! command -v nginx &> /dev/null; then
    echo "Nginx is not installed. Installing..."
    sudo apt update
    sudo apt install nginx -y
fi

default_config="/etc/nginx/sites-enabled/default"
rm "$default_config"
ln -s /etc/nginx/sites-available/default "$default_config"

# Restart Nginx to apply changes
sudo service nginx restart
