#!/usr/bin/env bash
# this is a bash script that make 8.8.8.8 as facebook.com
# change localhost to 127.0.0.2
cp /etc/hosts ~/hosts.new
echo "127.0.0.2		localhost" > ~/hosts.new
echo "8.8.8.8		facebook.com" >> ~/hosts.new
cp -f ~/hosts.new /etc/hosts
