#!/usr/bin/env bash
# This script displays all active IPv4 IPs on the machine.

# Use ifconfig to display active IPv4 IPs
ifconfig | grep -Eo 'inet (addr:)?([0-9]*\.){3}[0-9]*' | awk '{gsub(/inet (addr:)?/,""); print $1}'

