#!/usr/bin/env bash
# This script configures Nginx to run as the nginx user.

# Modify the nginx.conf file to change the user to nginx
sed -i 's/user\s*root;/user nginx;/g' /etc/nginx/nginx.conf

# Restart Nginx to apply the changes
service nginx restart

